name: CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          # Laravel 10 - supports PHP 8.1+
          - php-version: '8.1'
            laravel-version: '10.*'
          - php-version: '8.2'
            laravel-version: '10.*'
          - php-version: '8.3'
            laravel-version: '10.*'
          - php-version: '8.4'
            laravel-version: '10.*'
          # Laravel 11 - requires PHP 8.2+
          - php-version: '8.2'
            laravel-version: '11.*'
          - php-version: '8.3'
            laravel-version: '11.*'
          - php-version: '8.4'
            laravel-version: '11.*'
          # Laravel 12 - requires PHP 8.2+
          - php-version: '8.2'
            laravel-version: '12.*'
          - php-version: '8.3'
            laravel-version: '12.*'
          - php-version: '8.4'
            laravel-version: '12.*'

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, dom, fileinfo, mysql

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-laravel-${{ matrix.laravel-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-laravel-${{ matrix.laravel-version }}-

      - name: Remove composer.lock
        run: rm -f composer.lock

      - name: Require correct Laravel version
        run: |
          composer require "laravel/framework:${{ matrix.laravel-version }}" "illuminate/support:${{ matrix.laravel-version }}" "illuminate/notifications:${{ matrix.laravel-version }}" --no-interaction --no-progress --with-all-dependencies
          if [[ "${{ matrix.laravel-version }}" == "10.*" ]]; then
            composer require "orchestra/testbench:^8.0" --no-interaction --no-progress --with-all-dependencies
          elif [[ "${{ matrix.laravel-version }}" == "11.*" ]]; then
            composer require "orchestra/testbench:^9.0" --no-interaction --no-progress --with-all-dependencies
          else
            composer require "orchestra/testbench:^10.0" --no-interaction --no-progress --with-all-dependencies
          fi

      - name: Run tests
        run: composer test
