name: Update Packagist

on:
  push:
    tags: ["*"]
  release:
    types: [published]

jobs:
  update-packagist:
    runs-on: ubuntu-latest

    steps:
      - name: Update Packagist
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://packagist.org/api/update-package"
          method: "POST"
          data: '{"repository": {"url": "https://github.com/sureshhemal/laravel-sms-sri-lanka"}}'
          customHeaders: '{"Authorization": "Bearer ${{ secrets.PACKAGIST_TOKEN }}"}'
          timeout: 30000
